
package com.laegler.openbanking.soap.service;

import javax.xml.ws.WebFault;


/**
 * Internal Server Error
 *
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-21T07:01:26.683+13:00
 * Generated source version: 3.3.3
 */

@WebFault(name = "POST_CreateacallbackURL_500", targetNamespace = "http://laegler.com/openbanking/soap/model")
public class POSTCreateacallbackURL500 extends Exception {

    private com.laegler.openbanking.soap.model.OBErrorResponse1 postCreateacallbackURL500;

    public POSTCreateacallbackURL500() {
        super();
    }

    public POSTCreateacallbackURL500(String message) {
        super(message);
    }

    public POSTCreateacallbackURL500(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public POSTCreateacallbackURL500(String message, com.laegler.openbanking.soap.model.OBErrorResponse1 postCreateacallbackURL500) {
        super(message);
        this.postCreateacallbackURL500 = postCreateacallbackURL500;
    }

    public POSTCreateacallbackURL500(String message, com.laegler.openbanking.soap.model.OBErrorResponse1 postCreateacallbackURL500, java.lang.Throwable cause) {
        super(message, cause);
        this.postCreateacallbackURL500 = postCreateacallbackURL500;
    }

    public com.laegler.openbanking.soap.model.OBErrorResponse1 getFaultInfo() {
        return this.postCreateacallbackURL500;
    }
}
