
package com.laegler.openbanking.soap.service;

import javax.xml.ws.WebFault;


/**
 * Too Many Requests
 *
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-21T07:01:27.328+13:00
 * Generated source version: 3.3.3
 */

@WebFault(name = "PUT_AmendacallbackURI_429", targetNamespace = "http://laegler.com/openbanking/soap/model")
public class PUTAmendacallbackURI429 extends Exception {

    private java.lang.Object putAmendacallbackURI429;

    public PUTAmendacallbackURI429() {
        super();
    }

    public PUTAmendacallbackURI429(String message) {
        super(message);
    }

    public PUTAmendacallbackURI429(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PUTAmendacallbackURI429(String message, java.lang.Object putAmendacallbackURI429) {
        super(message);
        this.putAmendacallbackURI429 = putAmendacallbackURI429;
    }

    public PUTAmendacallbackURI429(String message, java.lang.Object putAmendacallbackURI429, java.lang.Throwable cause) {
        super(message, cause);
        this.putAmendacallbackURI429 = putAmendacallbackURI429;
    }

    public java.lang.Object getFaultInfo() {
        return this.putAmendacallbackURI429;
    }
}
