
package com.laegler.openbanking.soap.service;

import javax.xml.ws.WebFault;


/**
 * Unauthorized
 *
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-21T07:01:27.322+13:00
 * Generated source version: 3.3.3
 */

@WebFault(name = "PUT_AmendacallbackURI_401", targetNamespace = "http://laegler.com/openbanking/soap/model")
public class PUTAmendacallbackURI401 extends Exception {

    private java.lang.Object putAmendacallbackURI401;

    public PUTAmendacallbackURI401() {
        super();
    }

    public PUTAmendacallbackURI401(String message) {
        super(message);
    }

    public PUTAmendacallbackURI401(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PUTAmendacallbackURI401(String message, java.lang.Object putAmendacallbackURI401) {
        super(message);
        this.putAmendacallbackURI401 = putAmendacallbackURI401;
    }

    public PUTAmendacallbackURI401(String message, java.lang.Object putAmendacallbackURI401, java.lang.Throwable cause) {
        super(message, cause);
        this.putAmendacallbackURI401 = putAmendacallbackURI401;
    }

    public java.lang.Object getFaultInfo() {
        return this.putAmendacallbackURI401;
    }
}
