
package com.laegler.openbanking.soap.service;

import javax.xml.ws.WebFault;


/**
 * Not Acceptable
 *
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-21T07:01:27.329+13:00
 * Generated source version: 3.3.3
 */

@WebFault(name = "PUT_AmendacallbackURI_406", targetNamespace = "http://laegler.com/openbanking/soap/model")
public class PUTAmendacallbackURI406 extends Exception {

    private java.lang.Object putAmendacallbackURI406;

    public PUTAmendacallbackURI406() {
        super();
    }

    public PUTAmendacallbackURI406(String message) {
        super(message);
    }

    public PUTAmendacallbackURI406(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PUTAmendacallbackURI406(String message, java.lang.Object putAmendacallbackURI406) {
        super(message);
        this.putAmendacallbackURI406 = putAmendacallbackURI406;
    }

    public PUTAmendacallbackURI406(String message, java.lang.Object putAmendacallbackURI406, java.lang.Throwable cause) {
        super(message, cause);
        this.putAmendacallbackURI406 = putAmendacallbackURI406;
    }

    public java.lang.Object getFaultInfo() {
        return this.putAmendacallbackURI406;
    }
}
