
package com.laegler.openbanking.soap.service;

import javax.xml.ws.WebFault;


/**
 * Bad Gateway
 *
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-21T07:01:27.397+13:00
 * Generated source version: 3.3.3
 */

@WebFault(name = "PUT_Updatethebusinessorthetechnicalcontactsforthegivenorganisation_502", targetNamespace = "http://laegler.com/openbanking/soap/model")
public class PUTUpdatethebusinessorthetechnicalcontactsforthegivenorganisation502 extends Exception {

    private java.lang.Object putUpdatethebusinessorthetechnicalcontactsforthegivenorganisation502;

    public PUTUpdatethebusinessorthetechnicalcontactsforthegivenorganisation502() {
        super();
    }

    public PUTUpdatethebusinessorthetechnicalcontactsforthegivenorganisation502(String message) {
        super(message);
    }

    public PUTUpdatethebusinessorthetechnicalcontactsforthegivenorganisation502(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PUTUpdatethebusinessorthetechnicalcontactsforthegivenorganisation502(String message, java.lang.Object putUpdatethebusinessorthetechnicalcontactsforthegivenorganisation502) {
        super(message);
        this.putUpdatethebusinessorthetechnicalcontactsforthegivenorganisation502 = putUpdatethebusinessorthetechnicalcontactsforthegivenorganisation502;
    }

    public PUTUpdatethebusinessorthetechnicalcontactsforthegivenorganisation502(String message, java.lang.Object putUpdatethebusinessorthetechnicalcontactsforthegivenorganisation502, java.lang.Throwable cause) {
        super(message, cause);
        this.putUpdatethebusinessorthetechnicalcontactsforthegivenorganisation502 = putUpdatethebusinessorthetechnicalcontactsforthegivenorganisation502;
    }

    public java.lang.Object getFaultInfo() {
        return this.putUpdatethebusinessorthetechnicalcontactsforthegivenorganisation502;
    }
}
