
package com.laegler.openbanking.soap.service;

import javax.xml.ws.WebFault;


/**
 * Bad Gateway
 *
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-21T07:01:27.556+13:00
 * Generated source version: 3.3.3
 */

@WebFault(name = "PUT_Update.well-knownentity_502", targetNamespace = "http://laegler.com/openbanking/soap/model")
public class PUTUpdateWellKnownentity502 extends Exception {

    private java.lang.Object putUpdateWellKnownentity502;

    public PUTUpdateWellKnownentity502() {
        super();
    }

    public PUTUpdateWellKnownentity502(String message) {
        super(message);
    }

    public PUTUpdateWellKnownentity502(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PUTUpdateWellKnownentity502(String message, java.lang.Object putUpdateWellKnownentity502) {
        super(message);
        this.putUpdateWellKnownentity502 = putUpdateWellKnownentity502;
    }

    public PUTUpdateWellKnownentity502(String message, java.lang.Object putUpdateWellKnownentity502, java.lang.Throwable cause) {
        super(message, cause);
        this.putUpdateWellKnownentity502 = putUpdateWellKnownentity502;
    }

    public java.lang.Object getFaultInfo() {
        return this.putUpdateWellKnownentity502;
    }
}
