
package com.laegler.openbanking.soap.service;

import javax.xml.ws.WebFault;


/**
 * Not found
 *
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-21T07:01:27.557+13:00
 * Generated source version: 3.3.3
 */

@WebFault(name = "PUT_Update.well-knownentity_404", targetNamespace = "http://laegler.com/openbanking/soap/model")
public class PUTUpdateWellKnownentity404 extends Exception {

    private java.lang.Object putUpdateWellKnownentity404;

    public PUTUpdateWellKnownentity404() {
        super();
    }

    public PUTUpdateWellKnownentity404(String message) {
        super(message);
    }

    public PUTUpdateWellKnownentity404(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PUTUpdateWellKnownentity404(String message, java.lang.Object putUpdateWellKnownentity404) {
        super(message);
        this.putUpdateWellKnownentity404 = putUpdateWellKnownentity404;
    }

    public PUTUpdateWellKnownentity404(String message, java.lang.Object putUpdateWellKnownentity404, java.lang.Throwable cause) {
        super(message, cause);
        this.putUpdateWellKnownentity404 = putUpdateWellKnownentity404;
    }

    public java.lang.Object getFaultInfo() {
        return this.putUpdateWellKnownentity404;
    }
}
