
package com.laegler.openbanking.soap.service;

import javax.xml.ws.WebFault;


/**
 * Unauthorized
 *
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-21T07:01:27.558+13:00
 * Generated source version: 3.3.3
 */

@WebFault(name = "PUT_Update.well-knownentity_401", targetNamespace = "http://laegler.com/openbanking/soap/model")
public class PUTUpdateWellKnownentity401 extends Exception {

    private java.lang.Object putUpdateWellKnownentity401;

    public PUTUpdateWellKnownentity401() {
        super();
    }

    public PUTUpdateWellKnownentity401(String message) {
        super(message);
    }

    public PUTUpdateWellKnownentity401(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PUTUpdateWellKnownentity401(String message, java.lang.Object putUpdateWellKnownentity401) {
        super(message);
        this.putUpdateWellKnownentity401 = putUpdateWellKnownentity401;
    }

    public PUTUpdateWellKnownentity401(String message, java.lang.Object putUpdateWellKnownentity401, java.lang.Throwable cause) {
        super(message, cause);
        this.putUpdateWellKnownentity401 = putUpdateWellKnownentity401;
    }

    public java.lang.Object getFaultInfo() {
        return this.putUpdateWellKnownentity401;
    }
}
